spring:
  application:
    name: prices
  datasource:
    url: jdbc:h2:mem:productsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true